
<?php $__env->startSection('title', 'CV Builder'); ?>
<?php $__env->startSection('content'); ?>


<div class="container-fluid">
    <div class="row">
        <div class="col-6 mt-5 ">
            <!-- text left side open -->
            <h1 class="fw-special-title">IMPRESSIVE RESUMES <small>EASY ONLINE BUILDER</small></h1>
            <div class="text-block mt-5">
            
                <p><i class="fa fa-check mt-5"></i><span>Professional out-of-the-box resumes, instantly generated by the
                        most advanced resume builder technology available.</span></p>
                <p><i class="fa fa-check mt-5"></i><span>Effortless crafting. Real-time preview &amp; pre-written <a
                            href="">resume
                            examples</a>.<br />Dozens of HR-approved <a href="#"> resume templates</a>.</span></p>
                <p><i class="fa fa-check mt-5"></i><span>Land your dream job with the perfect resume employers are looking
                        for!</span></p>
            
        </div>
        <div class="button ">
            <a href="<?php echo e(route('user.create.cv')); ?>" class="btn btn-warning">
                Start My Resume </a>
            <!-- text left side close -->
        </div>

        </div>
        

        <div class="col-6 mt-5">
            <img src="<?php echo e(asset('assets/cv-img/2.png')); ?>" alt=""> 
        </div>
    </div>
</div>


<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.user-master', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\practice-code\mycv\resources\views/canva/index.blade.php ENDPATH**/ ?>